In [2]:
import numpy as np

In [ ]:
x = np.array([[1, 2, 3, 4, 5, 6, 7],
              [2, 3, 4, 5, 6, 7, 1],
              [3, 4, 5, 6, 7, 1, 2],
              [4, 5, 6, 7, 1, 2, 3],
              [5, 6, 7, 1, 2, 3, 4],
              [6, 7, 1, 2, 3, 4, 5],
              [7, 1, 2, 3, 4, 5, 6]])
x.shape

(7, 7)

In [4]:
f = np.array([[1, 2],
              [2, 3]])
f.shape

(2, 2)

In [5]:
stride = 1
pad = 1
image_h, image_w = x.shape[0], x.shape[1]
filter_h, filter_w = f.shape[0], f.shape[1]

X_train_padded = np.pad(x, ((1, 1), (1, 1)), mode = 'constant') # input padded

image_h_out = (((image_h + pad) - filter_h) // stride) + 1 
image_w_out = (((image_w + pad) - filter_w) // stride) + 1 

out = np.zeros((image_h_out, image_w_out))

for i in range(image_h_out):
    for j in range(image_w_out): 
        h_start = i * stride # height starting index for filter traversal
        h_end = h_start + filter_h # height ending index for filter traversal
        w_start = j * stride # width starting index for filter traversal
        w_end = w_start + filter_w # width ending index for filter traversal

        out[i, j] = np.sum(X_train_padded[h_start:h_end, w_start:w_end] * f[:, :]) 

print(out)

[[ 3.  8. 13. 18. 23. 28. 33.]
 [ 8. 18. 26. 34. 42. 50. 37.]
 [13. 26. 34. 42. 50. 37. 17.]
 [18. 34. 42. 50. 37. 17. 18.]
 [23. 42. 50. 37. 17. 18. 26.]
 [28. 50. 37. 17. 18. 26. 34.]
 [33. 37. 17. 18. 26. 34. 42.]]


In [ ]:
pool_h, pool_w = 2, 2 # height and width of pool region
stride = 2

image_h, image_w = x.shape[0], x.shape[1]

pool_h_out = (((image_h) - pool_h) // stride) + 1 
pool_w_out = (((image_w) - pool_w) // stride) + 1 

pooled_out = np.zeros((pool_h_out, pool_w_out))

for i in range(pool_h_out):
    for j in range(pool_w_out):
        pool_h_start = i * stride
        pool_h_end = pool_h_start + pool_h
        pool_w_start = j * stride
        pool_w_end = pool_w_start + pool_w

        pool_region = out[pool_h_start:pool_h_end, pool_w_start:pool_w_end] 
        pooled_out[i, j] = np.max(pool_region)

print(pooled_out)

[[18. 34. 50.]
 [34. 50. 50.]
 [50. 50. 26.]]


In [11]:
flat = pooled_out.reshape(1, -1)
print(flat)

[[18. 34. 50. 34. 50. 50. 50. 50. 26.]]


In [19]:
flat_norm = (flat - flat.mean()) / flat.std()
print(flat_norm)

[[-1.8844459  -0.52764485  0.8291562  -0.52764485  0.8291562   0.8291562
   0.8291562   0.8291562  -1.20604538]]


In [20]:
flat_sigmoid = 1 / (1 + np.exp(-flat_norm))
print(flat_sigmoid)

[[0.13187904 0.37106636 0.69617648 0.37106636 0.69617648 0.69617648
  0.69617648 0.69617648 0.23040152]]


In [22]:
input_features = flat_sigmoid.shape[1] 
neurons_layer1 = 10
neurons_layer2 = 1

w1 = np.random.randn(input_features, neurons_layer1)
w2 = np.random.randn(neurons_layer1, neurons_layer2)
b1 = np.random.randn(neurons_layer1)
b2 = np.random.randn(neurons_layer2)

hidden_out = np.dot(flat_sigmoid, w1) + b1 
affine_out = np.dot(hidden_out, w2) + b2 

In [27]:
y_pred = 1.0 / (1.0 + np.exp(-affine_out))
print(y_pred)

[[0.38100684]]


In [28]:
loss = np.sum(np.power((1 - y_pred), 2) / 2) / 1
print(loss)

0.19157626437517797
