In [1]:
import numpy as np

In [8]:
x = np.array([[1, 2, 3, 4, 5, 6, 7],
              [2, 3, 4, 5, 6, 7, 1],
              [3, 4, 5, 6, 7, 1, 2],
              [4, 5, 6, 7, 1, 2, 3],
              [5, 6, 7, 1, 2, 3, 4],
              [6, 7, 1, 2, 3, 4, 5],
              [7, 1, 2, 3, 4, 5, 6]])
x.shape

(7, 7)

In [6]:
f = np.array([[1, 2],
              [2, 3]])
f.shape

(2, 2)

In [32]:
stride = 1
pad = 1
image_h, image_w = x.shape[0], x.shape[1]
filter_h, filter_w = f.shape[0], f.shape[1]

X_train_padded = np.pad(x, ((1, 1), (1, 1)), mode = 'constant') # input padded

image_h_out = (((image_h + pad) - filter_h) // stride) + 1 
image_w_out = (((image_w + pad) - filter_w) // stride) + 1 

out = np.zeros((image_h_out, image_w_out))

for i in range(image_h_out):
    for j in range(image_w_out): 
        h_start = i * stride # height starting index for filter traversal
        h_end = h_start + filter_h # height ending index for filter traversal
        w_start = j * stride # width starting index for filter traversal
        w_end = w_start + filter_w # width ending index for filter traversal

        out[i, j] = np.sum(X_train_padded[h_start:h_end, w_start:w_end] * f[:, :]) 

print(out)

[[ 3.  8. 13. 18. 23. 28. 33.]
 [ 8. 18. 26. 34. 42. 50. 37.]
 [13. 26. 34. 42. 50. 37. 17.]
 [18. 34. 42. 50. 37. 17. 18.]
 [23. 42. 50. 37. 17. 18. 26.]
 [28. 50. 37. 17. 18. 26. 34.]
 [33. 37. 17. 18. 26. 34. 42.]]
